adminchat/urls.py
from django.urls import path
from . import views

app_name = 'adminchat'

urlpatterns = [
    path('chat/', views.chat_room, name='chat_room'),
    path('chat/admin/<str:room_name>/', views.chat_room, name='admin_chat_room'),
    path('chat/list/', views.chat_list, name='chat_list'),
]

core/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, \
    PasswordResetConfirmView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views
from .froms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),

    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),
         name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('category/<int:pk>/', views.category_products, name='category_products'),

    path('cart_add/<int:pk>/', views.add_cart, name='add_cart'),
    path('cart_remove/<int:pk>/', views.remove_cart, name='remove_cart'),
    path('cart/', views.cart, name='cart'),
    path('update/<int:pk>/<str:action>/', views.update_cart, name='update_cart'),
    path('cart/<int:pk>/', views.cart_detail, name='cart_detail'),
    path('allcartbuy/', views.all_cart_buy, name='all_cart_buy'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='core/password_reset_form.html',
                                                                 email_template_name='core/password_reset_email.html',
                                                                 success_url=reverse_lazy('core:password_reset_done')),
                                                                    name='password_reset'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'),
                                                    name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html',
                                                    success_url=reverse_lazy('core:password_reset_complete')),
                                                    name='password_reset_confirm'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'),
                                                        name='password_reset_complete'),
]

puddle/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from dashboard.admin import custom_admin_site


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('feedback/', include('feedback.urls')),
    path('admin-custom/', custom_admin_site.urls),
    path('help/', include('adminchat.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminchat/models.py
from django.db import models
from django.contrib.auth.models import User

class ChatMessage(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_messages')
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    room_name = models.CharField(max_length=255)  # Уникальное название комнаты

    def __str__(self):
        return f'{self.room_name} - {self.sender.username}: {self.message}'

adminchat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import ChatMessage

@login_required
def chat_room(request, room_name=None):
    if request.user.is_superuser and room_name:
        return render(request, 'adminchat/chat_room.html', {'room_name': room_name})

    room_name = f'user_{request.user.username}'
    return render(request, 'adminchat/chat_room.html', {'room_name': room_name})

@login_required
def chat_list(request):
    if not request.user.is_superuser:
        return render(request, 'adminchat/error.html', {'error': 'Доступ запрещен'})

    rooms = ChatMessage.objects.values('room_name').distinct()
    return render(request, 'adminchat/chat_list.html', {'rooms': rooms})

adminchat/templates/adminchat/chat_list.html
{% extends 'core/base.html' %}

{% block title %}Admin chat{% endblock %}

{% block content %}

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Chats list</h2>
    <ul>
        {% for room in rooms %}
            <li class="text-center"><a href="{% url 'adminchat:admin_chat_room' room.room_name %}">{{ room.room_name }}</a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

adminchat/templates/adminchat/chat_room.html
{% extends 'core/base.html' %}

{% block title %}Chat{% endblock %}

{% block content %}

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center" >Chat: {{ room_name }}</h2>

    <div class="bg-blue-100" id="chat-log"></div>
    <input id="chat-message-input" type="text" size="167.9">
    <button class="mt-6 py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white"
            id="chat-message-submit" >Send</button>
    <script>

        const roomName = "{{ room_name }}";
        const chatSocket = new WebSocket(
            `ws://${window.location.host}/ws/chat/${roomName}/`
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').innerHTML += `<p><strong>${data.username}:</strong> ${data.message}</p>`;
        };

        chatSocket.onclose = function(e) {
            console.error('WebSocket закрыт');
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({ message }));
            messageInputDom.value = '';
        };

        function sendMessage() {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value.trim();

            if (message) {
                chatSocket.send(JSON.stringify({ message }));
                messageInputDom.value = '';
            }
        }

        document.querySelector('#chat-message-submit').onclick = function(e) {
            sendMessage();
        };

        document.querySelector('#chat-message-input').onkeydown = function(e) {
            if (e.key === 'Enter') {
                e.preventDefault();
                sendMessage();
            }
        };
    </script>
</div>

{% endblock %}