adminchat/urls.py
from django.urls import path
from . import views

app_name = 'adminchat'

urlpatterns = [
    path('chat/', views.chat_room, name='chat_room'),
    path('chat/admin/<str:room_name>/', views.chat_room, name='admin_chat_room'),
    path('chat/list/', views.chat_list, name='chat_list'),
]

core/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, \
    PasswordResetConfirmView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views
from .froms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),

    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),
         name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('category/<int:pk>/', views.category_products, name='category_products'),

    path('cart_add/<int:pk>/', views.add_cart, name='add_cart'),
    path('cart_remove/<int:pk>/', views.remove_cart, name='remove_cart'),
    path('cart/', views.cart, name='cart'),
    path('update/<int:pk>/<str:action>/', views.update_cart, name='update_cart'),
    path('cart/<int:pk>/', views.cart_detail, name='cart_detail'),
    path('allcartbuy/', views.all_cart_buy, name='all_cart_buy'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='core/password_reset_form.html',
                                                                 email_template_name='core/password_reset_email.html',
                                                                 success_url=reverse_lazy('core:password_reset_done')),
                                                                    name='password_reset'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'),
                                                    name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html',
                                                    success_url=reverse_lazy('core:password_reset_complete')),
                                                    name='password_reset_confirm'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'),
                                                        name='password_reset_complete'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('edit/', views.edit, name='edit'),
]

feedback/urls.py
from django.urls import path
from . import views

app_name = 'feed'

urlpatterns = [
    path('feedback/', views.feedback, name='feedback'),
    path('feedback_info', views.feedback_info, name='feedback_info' )
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.item, name='items'),

    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),

    path('buy/<int:pk>/', views.buy, name='buy'),

    path('history/', views.history, name='history'),
]

puddle/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from dashboard.admin import custom_admin_site


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('feedback/', include('feedback.urls')),
    path('admin-custom/', custom_admin_site.urls),
    path('help/', include('adminchat.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User

from item.models import Item


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}'

core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from item.models import Category, Item, PurchaseHistory
from .models import Cart
from .froms import SignupForm
from django.contrib.auth import logout

from django.utils import timezone
from datetime import timedelta
import pickle



def create_purchase_history(user, product, quantity=1):
    PurchaseHistory.objects.create(
        user=user,
        image=product.image,
        name=product.name,
        price=product.price,
        quantity=quantity
    )


def index(request):
    now = timezone.now()
    week = now - timedelta(days=14)
    recent_products = Item.objects.filter(created_at__gte=week)


    top_items = recent_products.order_by('-purchases')[:6]
    categories = Category.objects.all()
    all_items = Item.objects.order_by('-created_at')[:6]


    return render(request, 'core/index.html', {'top_items': top_items,
                                                                   'categories': categories,
                                                                   'all_items': all_items})

def category_products(request, pk):
    category = get_object_or_404(Category, pk=pk)
    item = Item.objects.filter(category=category)

    return render(request, 'core/category_products.html', {'category': category,
                                                                                'items': item})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('/')


@login_required
def add_cart(request, pk):
    product = get_object_or_404(Item, pk=pk)
    cart_item, created = Cart.objects.get_or_create(
        user=request.user,
        product=product
    )

    if not created:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('/')

@login_required
def remove_cart(request, pk):
    product = get_object_or_404(Item, pk=pk)
    Cart.objects.filter(user=request.user, product=product).delete()
    return redirect('/cart')

@login_required
def cart(request):
    cart_items = Cart.objects.filter(user=request.user)
    total_price = sum(item.product.price * item.quantity for item in cart_items)

    return render(request, 'core/cart.html', {
        'cart_items': cart_items,
        'total_price': total_price
    })

@login_required
def update_cart(request, pk, action):
    product = get_object_or_404(Item, id=pk)
    cart_item, created = Cart.objects.get_or_create(user=request.user, product=product)

    if action == 'add':
        cart_item.quantity += 1
    elif action == 'remove':
        if cart_item.quantity > 1:
            cart_item.quantity -= 1

    cart_item.save()
    return redirect(f'/cart/{pk}/')

@login_required
def cart_detail(request, pk):
    product = get_object_or_404(Item, pk=pk)
    cart_items = Cart.objects.filter(user=request.user, product=product)
    total_item_price = sum(item.product.price * item.quantity for item in cart_items)

    return render(request, 'core/cart_detail.html', {'cart_items': cart_items,
                                                                        'total_item_price': total_item_price})

@login_required
def all_cart_buy(request):
    cart_items = Cart.objects.filter(user=request.user)

    for item in cart_items:
        create_purchase_history(request.user, item.product, item.quantity)

        new = get_object_or_404(Item, name=item.product)
        new.purchases += 1
        new.save()

    cart_items.delete()
    return redirect('/')

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>

    <title>{% block title %}{% endblock %} | Puddle</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Puddle</a>

        <div class="space-x-6">
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
            <a href="{% url 'item:history' %}" class="text-lg font-semibold hover:text-gray-500">History</a>
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'core:cart' %}" class="px-6 py-3
                 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">
                    Cart
                </a>

                <a href="{% url 'dashboard:index' %}" class="px-6 py-3
                 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">
                    Dashboard
                </a>
                <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold
                bg-gray-500 text-white rounded-xl hover:bg-gray-700">
                    Logout
                </a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold
                 bg-blue-500 text-white rounded-xl hover:bg-blue-700">
                    Sign up
                </a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold
                 bg-gray-500 text-white rounded-xl hover:bg-gray-700">
                    Log in
                </a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>

            <p class="text-lg text-gray-500">Pf abidna goida ratatatatata blabl ablabl ablablabla</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-1">
                <li><a href="{% url 'feed:feedback' %}" class="text-lg text-blue-500 hover:text-blue-700">feedback</a></li>
                <li><a href="{% url 'adminchat:chat_room' %}" class="text-lg text-blue-500 hover:text-blue-700">Support</a></li>
                <li><a href="{% url 'feed:feedback_info' %}" class="text-lg text-blue-500 hover:text-blue-700">Feed</a></li>
                <li><a href="#" class="text-lg text-blue-500 hover:text-blue-700">Term of use</a></li>
            </ul>

        </div>

    </footer>
</body>
</html>

core/templates/core/cart.html
{% extends 'core/base.html' %}

{% block title %}Cart{% endblock %}

{% block content %}

<a class="inline-block mt-6 px-6 py-3 text-lg
   font-semibold bg-blue-500 hover:bg-blue-700 text-white rounded-xl"
   href="{% url 'core:all_cart_buy' %}">buy everything</a>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Cart<br>total price: {{ total_price }}</h2>

    <div class="grid grid-cols-3 gap-3">
    {% for item in cart_items %}
            <div>
                <a href="{% url 'core:cart_detail' item.product.id %}">
                    <div>
                      <img style="height:65vh;width:700px;" src="{{ item.product.image.url }}"
                           class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.product.name }}</h2>
                        <p class="text-gray-500">price: {{ item.product.price }}</p>
                        <p class="text-gray-500">quantity: {{ item.quantity }}</p>
                    </div>
                </a>
            </div>
    {% endfor %}
    </div>
</div>

{% endblock %}

core/templates/core/cart_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}_cart{% endblock %}

{% block content %}
{% for item in cart_items %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.product.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.product.name }}</h1>
        {% if item.product.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ item.product.description }}
            </p>
        {% endif %}

        <p class="text-gray-500">Price: {{ item.product.price }}</p>
        <p class="text-gray-500">Quantity: {{ item.quantity }}</p>
        <p>Total price: {{ total_item_price }}</p>


        <div>

            <a class="inline-block mt-6 px-6 py-3 text-lg
               font-semibold bg-blue-500 hover:bg-blue-700 text-white rounded-xl"
               href="{% url 'core:update_cart' item.product.id 'add' %}">+</a>

            <a class="inline-block mt-6 px-6 py-3 text-lg
               font-semibold bg-blue-500 hover:bg-blue-700 text-white rounded-xl"
               href="{% url 'core:update_cart' item.product.id 'remove' %}">-</a>

            <a class="inline-block mt-6 px-6 py-3 text-lg
               font-semibold bg-red-500 hover:bg-red-700 text-white rounded-xl"
               href="{% url 'core:remove_cart' item.product.id %}">Delete</a>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

core/templates/core/category_products.html
{% extends 'core/base.html' %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">{{ category.name }} products</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                          <img style="height:65vh;width:700px;" src="{{ item.image.url }}"
                               class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Top products</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in top_items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                          <img style="height:65vh;width:700px;" src="{{ item.image.url }}"
                               class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">price: {{ item.price }}</p>
                            <p class="text-gray-500">purchases: {{ item.purchases }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>



    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">All products</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in all_items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                          <img style="height:65vh;width:700px;" src="{{ item.image.url }}"
                               class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">price: {{ item.price }}</p>
                            <p class="text-gray-500">purchases: {{ item.purchases }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>


    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <a href="{% url 'core:category_products' category.id %}">
                    <div class="p-6 bg-white rounded-b-xl hover:text-blue-500">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500">{{ category.items.count }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>
        <a href="{% url 'core:password_reset' %}">Forgot my password</a>
    </form>
</div>
{% endblock %}

core/templates/core/password_reset_complete.html
{% extends 'core/base.html' %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">

    <h2>Password changed successfully!</h2>
    <a href="{% url 'core:login' %}">Now you can login with new password</a>

</div>

{% endblock %}

core/templates/core/password_reset_confirm.html
{% extends 'core/base.html' %}

{% block content %}

<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Reset password</h1>

    <h2>Enter new password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button class="mt-6 py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white"
                type="submit">Change password</button>
    </form>

</div>
{% endblock %}

core/templates/core/password_reset_done.html
{% extends "core/base.html" %}
{% load i18n %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Reset password</h1>

    <h2>Letter sent!</h2>
    <p>Check your email for further instructions.</p>
</div>


{% endblock %}

core/templates/core/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'core:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

core/templates/core/password_reset_form.html
{% extends 'core/base.html' %}

{% block title %}Reset{% endblock %}

{% block content %}

<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Reset password</h1>

    <p>Enter your email address to receive a password reset link:</p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="mt-6 py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white"
                type="submit">Send</button>
    </form>

</div>


{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}