core/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, \
    PasswordResetConfirmView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views
from .froms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),

    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),
         name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('category/<int:pk>/', views.category_products, name='category_products'),

    path('cart_add/<int:pk>/', views.add_cart, name='add_cart'),
    path('cart_remove/<int:pk>/', views.remove_cart, name='remove_cart'),
    path('cart/', views.cart, name='cart'),
    path('update/<int:pk>/<str:action>/', views.update_cart, name='update_cart'),
    path('cart/<int:pk>/', views.cart_detail, name='cart_detail'),
    path('allcartbuy/', views.all_cart_buy, name='all_cart_buy'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='core/password_reset_form.html',
                                                                 email_template_name='core/password_reset_email.html',
                                                                 success_url=reverse_lazy('core:password_reset_done')),
                                                                    name='password_reset'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'),
                                                    name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html',
                                                    success_url=reverse_lazy('core:password_reset_complete')),
                                                    name='password_reset_confirm'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'),
                                                        name='password_reset_complete'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.item, name='items'),

    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),

    path('buy/<int:pk>/', views.buy, name='buy'),

    path('history/', views.history, name='history'),
]

puddle/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from dashboard.admin import custom_admin_site


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('feedback/', include('feedback.urls')),
    path('admin-custom/', custom_admin_site.urls),
    path('help/', include('adminchat.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Item(models.Model):

    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    purchases = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name


class PurchaseHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='purchases')
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    price = models.FloatField()
    quantity = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'History: {self.name} - {self.price}'

item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from .forms import NewItemForm, EditItemForm
from .models import Item, Category, PurchaseHistory


def create_purchase_history(user, product, quantity=1):
    PurchaseHistory.objects.create(
        user=user,
        image=product.image,
        name=product.name,
        price=product.price,
        quantity=quantity
    )


def item(request):
    query = request.GET.get('query', '')
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    category_id = request.GET.get('category', 0)

    start_price = request.GET.get('start_price')
    end_price = request.GET.get('end_price')

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    if start_price and end_price:
        items = items.filter(price__range=(start_price, end_price))

    paginator = Paginator(items, 6)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'item/items.html', context={'items': items,
                                                       'query': query,
                                                       'categories': categories,
                                                       'category_id': int(category_id),
                                                       'page_obj': page_obj})

def detail(request, pk):

    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', context={'item': item, 'related_items': related_items})


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)

    else:
        form = NewItemForm()

    return render(request, 'item/form.html', context={'form': form, 'title': 'New item'})


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)

    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', context={'form': form, 'title': 'Edit item'})


@login_required
def buy(request, pk):
    user = request.user
    product = Item.objects.get(pk=pk)
    quantity = int(request.POST.get('quantity', 1))
    create_purchase_history(user, product, quantity)

    item = get_object_or_404(Item, pk=pk)
    item.purchases += 1
    item.save()

    return render(request, 'item/detail.html', {'item': item})

@login_required
def history(request):
    history = PurchaseHistory.objects.filter(user=request.user).order_by('-created_at')

    return render(request, 'item/history.html', {'history': history})

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-500">Price: {{ item.price }}</p>
        <p class="text-gray-500">Seller: {{ item.created_by }}</p>

        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ item.description }}
            </p>
        {% endif %}

        {% if request.user ==  item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your item!</p>

                <a href="{% url 'item:edit' item.id %}"
                   class="inline-block mt-6 px-6 py-3 text-lg
                    font-semibold bg-blue-500 hover:bg-blue-700 text-white rounded-xl">Edit</a>

                <a href="{% url 'item:delete' item.id %}"
                   class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
            </div>
        {% else %}
            <div>
                <a href="{% url 'item:buy' item.id %}"
                   class="inline-block mt-6 px-6 py-3 text-lg
                    font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Buy</a>
                <a href="{% url 'core:add_cart' item.id %}"
                   class="inline-block mt-6 px-6 py-3 text-lg
                    font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Cart</a>
            </div>
            <p class="mt-6  py-3">Покупки: {{ item.purchases }}</p>
        {% endif %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related products</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                      <img style="height:65vh;width:700px;" src="{{ item.image.url }}"
                           class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ title }}</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-4">
            {{form.as_p}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="mt-6 py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>

    </form>
{% endblock %}

item/templates/item/history.html
{% extends 'core/base.html' %}

{% block title %}History{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">History</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in history %}
                <div>
                    <div>
                      <img style="height:65vh;width:700px;" src="{{ item.image.url }}"
                           class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">price: {{ item.price }}</p>
                        <p class="text-gray-500">time: {{ item.created_at }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Items{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'item:items' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text"
                       value="{{ query }}" placeholder="Find need product">

                <button class="mt-2 py-6 px-8 text-lg bg-blue-500 hover:bg-blue-700 text-white rounded-xl">
                    Search
                </button>
            </form>

            <hr class="my-6">

            <p class="font-semibold">Categories</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl hover:bg-gray-200">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id}}">
                            {{ category.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <form method="get">
                <input id="start_price" name="start_price">
                <input id="end_price" name="end_price">
                <button type="submit">Search</button>
            </form>

            <hr class="my-6">

            <p class="font-semibold">Clear filters</p>

            <ul>
                <li>
                    <a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block
                     bg-yellow-500 hover:bg-yellow-700 text-lg rounded-xl text-white">
                        Clear
                    </a>
                </li>
            </ul>
        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for item in page_obj %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img style="height:65vh;width:700px;" src="{{ item.image.url }}"
                                class="rounded-t-xl">
                            </div>

                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>


        <div class="pagination">
            <span>
                Page {{ page_obj.number }} in {{ page_obj.paginator.num_pages }}
            </span>
        </div>

        <div class="mt-6">
            {% if page_obj.has_previous %}
                <a class="mt-6 py-4 px-8 text-lg bg-blue-500
                 hover:bg-blue-700 rounded-xl text-white" href="?page=1">Первая</a>
                <a class="mt-6 py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700
                 rounded-xl text-white" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <strong class="mt-6 py-4 px-8 text-lg bg-blue-500
                    hover:bg-blue-700 rounded-xl text-white">{{ num }}</strong>
                {% else %}
                    <a class="mt-6 py-4 px-8 text-lg bg-blue-500
                    hover:bg-blue-700 rounded-xl text-white" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="mt-6 py-4 px-8 text-lg bg-blue-500
                hover:bg-blue-700 rounded-xl text-white" href="?page={{ page_obj.next_page_number }}">Следующая</a>
                <a class="mt-6 py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700
                 rounded-xl text-white" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
            {% endif %}
        </div>

        </div>
    </div>
{% endblock %}