core/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, \
    PasswordResetConfirmView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views
from .froms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),

    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),
         name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('category/<int:pk>/', views.category_products, name='category_products'),

    path('cart_add/<int:pk>/', views.add_cart, name='add_cart'),
    path('cart_remove/<int:pk>/', views.remove_cart, name='remove_cart'),
    path('cart/', views.cart, name='cart'),
    path('update/<int:pk>/<str:action>/', views.update_cart, name='update_cart'),
    path('cart/<int:pk>/', views.cart_detail, name='cart_detail'),
    path('allcartbuy/', views.all_cart_buy, name='all_cart_buy'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='core/password_reset_form.html',
                                                                 email_template_name='core/password_reset_email.html',
                                                                 success_url=reverse_lazy('core:password_reset_done')),
                                                                    name='password_reset'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'),
                                                    name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html',
                                                    success_url=reverse_lazy('core:password_reset_complete')),
                                                    name='password_reset_confirm'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'),
                                                        name='password_reset_complete'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('edit/', views.edit, name='edit'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.item, name='items'),

    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),

    path('buy/<int:pk>/', views.buy, name='buy'),

    path('history/', views.history, name='history'),
]

puddle/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from dashboard.admin import custom_admin_site


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('feedback/', include('feedback.urls')),
    path('admin-custom/', custom_admin_site.urls),
    path('help/', include('adminchat.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from item.models import Item

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

from item.models import Item
from .forms import UserForm

@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user)

    return render(request, 'dashboard/index.html', context={'items': items})


@login_required
def edit(request):
    user = request.user
    if request.method == 'POST':
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('/dashboard/')
    else:
        form = UserForm(instance=user)

    return render(request, 'dashboard/edit.html', {'user': user, 'form': form})

@login_required
def new_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('/dashboard/')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'dashboard/new_password.html', {'form': form})

dashboard/templates/dashboard/edit.html
{% extends 'core/base.html' %}

{% block title %}Edit profile{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Edit</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Profile</h2>

        <div class="mb-12 text-2xl text-center">
            <h2>Username: {{ user.username }}</h2>
            <h2>Email: {{ user.email }}</h2>
            <h2 class="mb-12">Products: {{ items.count }}</h2>
            <a href="{% url 'dashboard:edit' %}" class="px-6 py-3
                 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">edit profile</a>
            <a href="{% url 'core:password_reset' %}" class="text-lg font-semibold hover:text-gray-500">password reset</a>
        </div>

    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">My products</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                          <img style="height:65vh;width:700px;" src="{{ item.image.url }}"
                               class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/new_password.html
{% extends 'core/base.html' %}

{% block title %}Edit password{% endblock %}


{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Edit</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="inline-block mb-2" >Old password:</label>
            {{ form.old_password }}
            {{ form.old_password.errors }}
        </div>
        <div class="form-group">
            <label class="inline-block mb-2" >New password:</label>
            {{ form.new_password1 }}
            {{ form.new_password1.errors }}
        </div>
        <div class="form-group">
            <label class="inline-block mb-2" >New password again:</label>
            {{ form.new_password2 }}
            {{ form.new_password2.errors }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-blue-500 hover:bg-blue-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}